// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ModuloDeUrgenciasFeature : object, Xunit.IClassFixture<ModuloDeUrgenciasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Modulo de Urgencias", "  Esta feature esta relacionada al registro de ingresos de pacientes en la sala d" +
                "e urgencias,\r\n  respetando su nivel de prioridad y el horario de llegada.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ModuloUrgencias.feature"
#line hidden
        
        public ModuloDeUrgenciasFeature(ModuloDeUrgenciasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Nombre",
                        "Apellido"});
            table1.AddRow(new string[] {
                        "Susana",
                        "Gimenez"});
#line 6
  await testRunner.GivenAsync("que la siguiente enfermera esta registrada:", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente de bajo nivel de emergencia y luego otro de alto nivel de " +
            "emergencia")]
        [Xunit.TraitAttribute("FeatureTitle", "Modulo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente de bajo nivel de emergencia y luego otro de alto nivel de " +
            "emergencia")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteDeBajoNivelDeEmergenciaYLuegoOtroDeAltoNivelDeEmergencia()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente de bajo nivel de emergencia y luego otro de alto nivel de " +
                    "emergencia", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "CUIL",
                            "Apellido",
                            "Nombre",
                            "Obra Social"});
                table2.AddRow(new string[] {
                            "23-1234567-9",
                            "Nunez",
                            "Marcelo",
                            "Subsidio de Salud"});
                table2.AddRow(new string[] {
                            "23-4567899-2",
                            "Estrella",
                            "Patricio",
                            "Fondo de Bikini SA"});
#line 11
  await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table2, "Given ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "CUIL",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table3.AddRow(new string[] {
                            "23-4567899-2",
                            "Le duele el ojo",
                            "SIN_URGENCIA",
                            "37",
                            "70",
                            "15",
                            "120/80"});
                table3.AddRow(new string[] {
                            "23-1234567-9",
                            "Le agarro dengue",
                            "EMERGENCIA",
                            "38",
                            "70",
                            "15",
                            "120/80"});
#line 15
  await testRunner.WhenAsync("Ingresan a urgencias los siguientes pacientes:", ((string)(null)), table3, "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "CUIL"});
                table4.AddRow(new string[] {
                            "23-1234567-9"});
                table4.AddRow(new string[] {
                            "23-4567899-2"});
#line 19
  await testRunner.ThenAsync("La lista de espera esta ordenada por cuil de la siguiente manera:", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar ingreso con valores negativos en Frecuencia Cardiaca")]
        [Xunit.TraitAttribute("FeatureTitle", "Modulo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Registrar ingreso con valores negativos en Frecuencia Cardiaca")]
        public async System.Threading.Tasks.Task RegistrarIngresoConValoresNegativosEnFrecuenciaCardiaca()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar ingreso con valores negativos en Frecuencia Cardiaca", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "CUIL",
                            "Apellido",
                            "Nombre",
                            "Obra Social"});
                table5.AddRow(new string[] {
                            "23-12345678-7",
                            "Gomez Rivera",
                            "Pablo",
                            "Swiss Medical"});
#line 25
  await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table5, "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "CUIL",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table6.AddRow(new string[] {
                            "23-12345678-7",
                            "Le duele la pestana",
                            "SinUrgencia",
                            "37",
                            "-70",
                            "15",
                            "120/80"});
#line 28
  await testRunner.WhenAsync("Ingresan a urgencias los siguientes pacientes:", ((string)(null)), table6, "When ");
#line hidden
#line 31
  await testRunner.ThenAsync("el sistema muestra el siguiente error: \"La frecuencia cardíaca no puede ser negat" +
                        "iva\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ModuloDeUrgenciasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ModuloDeUrgenciasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
